name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Poetry and Dependencies
      run: |
        pip install poetry
        poetry install
    - name: Lint with flake8
      run: |
        poetry run flake8 . --count --max-complexity=10 --max-line-length=120 --statistics
      working-directory: ./src
    - name: Static Typechecking with MyPy
      run: |
        poetry run mypy -p secrets_tool
      working-directory: ./src
